#! /bin/sh

#./panel &

###

bspc config border_width 1
bspc config window_gap 25

bspc config normal_border_color "#353540"
bspc config focused_border_color "#8292b2"
bspc config presel_border_color "#9db270"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc rule -a Gimp floating=on
bspc rule -a mpv floating=on
bspc rule -a feh floating=on # manage=off
