#!/bin/sh

### Panel stuff

panel_height=16
stlarch_font="-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1"
#panel_font=-"xos4-terminesspowerline-medium-r-normal--12-*-*-*-*-*-iso10646-*"
#panel_font="-*-terminus-medium-*-*-*-12-*-*-*-*-*-iso10646-*"
#panel_font="-*-lemon-medium-*-*-*-10-*-*-*-*-*-iso8859-*"
#panel_font="-misc-fixed-medium-r-semicondensed-*-13-*-*-*-*-*-iso10646-*"
panel_font="-*-tewi-medium-*-normal--*-*-*-*-*-*-iso10646-*"

### Satori by Kori-ayakashi, slightly modded by me


bg="#FF09090d"
fg="#FFedeff2"
black="#FF353540"
black2="#FF545466"
red="#FF8c5760"
red2="#FFb26f7a"
green="#FF7b8c58"
green2="#FF9db270"
yellow="#FF8c6e43"
yellow2="#FFb28c55"
blue="#FF58698c"
blue2="#FF7086b2"
magenta="#FF7b5e7d"
magenta2="#FF9c77b2"
cyan="#FF66808c"
cyan2="#FF82a2b2"
white="#FF8c8b8b"
white2="#FFb8b8c8"

blue3="#FF8292b2"
white3="#FFe2e5ea"
black3="#FF1f1f22"

### Desktops

desktop_focused="%{F$yellow2} %{F-}"
desktop_busy="%{F$blue2} %{F-}"
desktop_free="%{F$black2} %{F-}"

### Music

#music_suffix="%{B-}%{F$black}%{F-}"

#mpd_controls="%{F$red2}%{A:mpc -q single:}  %{A}%{F-}"
#mpd_controls+="%{F$green2}%{A:mpc -q repeat:} %{A}%{F-}"
#mpd_controls+="%{F$yellow2}%{A:mpc -q random:} %{A}%{F-}"
#mpd_controls+="%{F$magenta2}%{A:mpc -q consume:} %{A}%{F-}"
#
#status="%{B$black}%{F-}"
#status_controls="%{B$bg}%{F-}%{B$bg}$mpd_controls%{B$black}%{F$bg}%{F-}%{B$black}"

#music_icon="%{A:mpc -q toggle:}%{B$blue}  %{B-}%{F$blue}%{A}$status"
#paused_icon="%{A:mpc -q toggle:}%{B$red}  %{B-}%{F$red}%{A}$status"

music_icon="%{F$blue3}%{B$black3}  %{B-} %{F-}"
paused_icon="%{F$red}%{B$black3}  %{B-} %{F-}"

#prev_icon="%{A:mpc -q prev:} %{A}"
#pause_icon="%{A:mpc -q pause:} %{A}"
#play_icon="%{A:mpc -q play:} %{A}"
#next_icon="%{A:mpc -q next:} %{A}"

### Volume

#vol_icon="%{F#FF7b8c58}" . "" . "%{F-}%{B#FF7b8c58}" . "  " . "%{F#FF353540}" . "" . "%{B#FF353540}%{F-} ";
#muted_icon="%{F#FF8c5760}" . "" . "%{F-}%{B#FF8c5760}" . "  " . "%{F#FF353540}" . "" . "%{B#FF353540}%{F-} ";

vol_icon="%{F$green2}%{B$black3}  %{B-} %{F-}"
muted_icon="%{F$red}%{B$black3}  %{B-} %{F-}"

### Clock

#clock_icon="%{F$cyan}%{F-}%{B$cyan}  %{F$black}%{B$black} %{F-}%{B-}"
#clock_format="c$clock_icon%{B$black}%I:%M %p - %d/%m %{B-}"

clock_icon="%{F$cyan2}%{B$black3}  %{B-} %{F-}"
clock_format="c$clock_icon%I:%M %p - %a, %d %b %{F-}"

#clock_icon="^fg($cyan)^fg()^bg($cyan) clock ^fg($cyan)^bg($black) ^fg()^bg()"
#clock_format="%I:%M %p - %d/%m"

### Powerline icons

#     |   


### Bar
barch=""
barfg="%{F$fg}"
barbg="%{F$black}"

makebar() {
	max=10
	cur=$(($1 / 10))

	for v in {0..9}; do
		if [[ $v -lt $cur ]]; then
			bar+=$barfg$barch
		else
			bar+=$barbg$barch
		fi
	done

	echo $bar
}
