#! /bin/bash

. "$(dirname $0)/panel-settings"

while read -r line ; do
	case $line in
		m*)
			music="${line#?} " ;;
		v*)
			volume="${line#?}" ;;
		c*)
			clock="${line#?}" ;;
		n*)
			notifs="${line#?}" ;;
		w*)
			wifi="${line#?}" ;;
		W*)
			wm_infos=""
			IFS=":"
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[OFU]*)
						# focused desktop
						wm_infos+="%{A:bspc desktop -f $name:}$desktop_focused%{A}"
						;;
					o*)
						# busy desktop
						wm_infos+="%{A:bspc desktop -f $name:}$desktop_busy%{A}" 
						;;	
					f*)
						# free desktop
						wm_infos+="%{A:bspc desktop -f $name:}$desktop_free%{A}" 
						;;
					#L*)
					#	# layouts
					#	title="$title ${name}" ;;
				esac
				shift
			done ;;
	esac
	printf "%s\n" "%{l}$music%{c}$wm_infos%{r}$wifi$volume $clock $notifs"
done
