#! /bin/sh

export PATH=$PATH:$PWD

panel &

###

bspc config border_width 1
bspc config window_gap 24

bspc config normal_border_color "#101017"
bspc config focused_border_color "#edeff2"
bspc config presel_border_color "#7086b2"
bspc config urgent_border_color "#b26f7a"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

# Rules
bspc rule -a Gimp pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a feh floating=on manage=off
