#! /usr/bin/perl -CS
# vim:et:

use strict;
use warnings;
use POSIX qw(strftime);
# chr(0xE1CD)
# chr(0xE015)
my $full = strftime 'DATE:'
                  . ' %A, %d of %B '
                  . 'TIME:'
                  . " %H:%M:%S\n", localtime;


print $full;
