#!/usr/bin/bash

URL=$(xclip -o)
INFO=$(youtube-dl -f $URL)
COOKIE="$HOME/.config/mpv/cookie.txt"

notify() {
	notify-send -i "/usr/share/icons/hicolor/32x32/apps/mpv.png" "MPV-YT" "$1"
}

# Glorious bash "error checking". Fucking disgusting.
_check() {
	if [ $? -gt 0 ]; then 
		notify "Something went wrong."
	fi
}

if [[ $URL =~ "http" ]]; then
	notify "Playing video..."
	VIDEO=$(youtube-dl -g --cookies $COOKIE -f 43 $URL)
	
	_check

	mpv --cookies --cookies-file $COOKIE $VIDEO

	_check
else
	notify "Not a valid URL."
fi
