#!/usr/bin/bash

NAME="$(basename $0)"
COOKIE="$HOME/.config/mpv/cookie.txt"
URL=${1:-`xclip -o`}

notify() {
	notify-send -i "/usr/share/icons/hicolor/32x32/apps/mpv.png" $NAME "$1"
}

if [[ $URL =~ "http" ]]; then
	notify "Playing video..."
	VIDEO=$(youtube-dl -g --cookies $COOKIE -f 43 $URL)
	
	[ $? -gt 0 ] && notify "youtube-dl failed to start."

	mpv --cookies --cookies-file $COOKIE $VIDEO

	[ $? -gt 0 ] && notify "mpv failed to start."
else
	notify "Not a valid URL."
fi
