#!/bin/sh

TARGET_ICON=/usr/share/icons/hicolor/48x48/apps/applications-internet.png
ICON=/tmp/net_reload_icon.png
SUCCESS="DodgerBlue"
FAILURE="Red"

colorize_icon() { 
	convert ${TARGET_ICON} +level-colors ,${1} ${ICON} 
}

net_notify() {
	if [[ $1 == 1 ]]; then
		colorize_icon $SUCCESS
		shift
	else
		colorize_icon $FAILURE
	fi

	notify-send -i $ICON "DHCPCD" "$@"
}

while true; do
	sudo pkill -x dhcpcd

	DHCPCD=$(sudo dhcpcd -4 2>&1)
	RESULT=$(echo $DHCPCD | tail -c 128)

	echo $RESULT

	if [[ $RESULT =~ "sending commands to master" ]]; then
		net_notify "Failed to kill DHCPCD"
	elif [[ $RESULT =~ "timed out" ]]; then
		net_notify "Timed out."
	elif [[ $RESULT =~ "no interfaces have a carrier" ]]; then
		net_notify "Wi-Fi is down."
	else
		net_notify 1 "Restart successful."
		break
	fi

done
