if (( ! $+commands[python] && ! $+commands[pip] )) {
	return 1
}

# Autogenerated from pip completion --zsh
pip_cache="$HOME/.pip.cache.zsh"

if [[ $commands[pip] -nt "$pip_cache" || ! -s "$pip_cache" ]] {
	pip completion --zsh >| "$pip_cache"
}

source "$pip_cache"
unset pip_cache
