#! /bin/sh

. panel-settings

#WIFI ICONS
#
NAME=`iwconfig wlp1s10 | sed -n 's/.*ESSID:\"\(.*\)\".*/\1/p'`
QUAL=`iwconfig wlp1s10 | sed -n 's/Link Quality=\([0-9]\+\)\/.*/\1/p'`
MAX=`iwconfig wlp1s10 | sed -n 's/Link Quality=.*\/\([0-9]\+\).*/\1/p'`
PERC=`echo $QUAL*100/$MAX | bc`
icon=""

while true; do
case $PERC in
	[0-4])
		icon="%{F$red2}%{F-}"
		;;
	[4-9])
		icon="%{F$magenta2}%{F-}"
		;;
	[2-3]*)
		icon="%{F$blue2}%{F-}"
		;;
	[4-5]*)
		icon="%{F$yellow2}%{F-}"
		;;
	[6-7]*)
		icon="%{F$cyan2}%{F-}"
		;;
	*)
		icon="%{F$green2}%{F-}"
		;;
esac

echo "w%{B$black3} $icon %{B-} $NAME " > $PANEL_FIFO
sleep 60
done
