#! /bin/sh

export SXHKD_SHELL=/bin/sh
sxhkd &

BASEDIR="$(dirname $(readlink -f $0))"

$BASEDIR/lemonpanel &

# export PATH=$PATH:$(dirname $0)

###

# Config
bspc config border_width 4
bspc config window_gap 24


bspc config normal_border_color  "$(xrq color0)"
bspc config focused_border_color "$(xrq color1)"
bspc config presel_feedback_color  "$(xrq color1)"


bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config history_aware_focus true


bspc monitor -d I II III IV V VI VII VIII IX X

# Rules
bspc rule -a gimp pseudo_tiled=on
# bspc rule -a feh floating=on
bspc rule -a firefox desktop=^1 fullscreen=on focus=on
bspc rule -a emacs tiled=on
bspc rule -a lemonpanel manage=on layer=below

# Fix full screen issue
xdo lower (xdo id -a lemonpanel)
