#! /bin/sh

BASEDIR="$(dirname $0)"

# export PATH=$PATH:$(dirname $0)

###

# Config
bspc config border_width 1
bspc config window_gap 24

bspc config normal_border_color "#2b303b"
bspc config focused_border_color "#8fa1b3"
bspc config presel_border_color "#ebcb8b"
bspc config urgent_border_color "#bf616a"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cacenl true

bspc monitor -d I II III IV V VI VII VIII IX X

# Rules
bspc rule -a Gimp pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a feh floating=on manage=off
bspc rule -a Chromium desktop=^1 fullscreen=on focus=on

# Loop
if test -e "$BSPWM_TREE"; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

# TODO: Put panel here.
