#!/bin/sh

BASEDIR="$(dirname $(readlink -f $0))"
HEIGHT=16

bspc config top_padding $HEIGHT

function die {
	bspc config top_padding 0
	trap - TERM
	kill 0
}

trap die TERM INT QUIT EXIT

ruby $BASEDIR/panel/app.rb | 
	lemonbar -f '-*-tewi-medium-*-*-*-*-*-*-*-*-*-*-*' -g x$HEIGHT -u 4 -a 32 -n lemonpanel | 
	sh &

sleep 0.25

# xdo lower $(xdo id -a lemonpanel)

wait
