#! /bin/sh

. panel-settings

while true; do
	status=`mpc status`
	song=`mpc current`

	if [[ $status =~ "playing" ]]; then
		icon="$music_icon"
	elif [[ $status =~ "paused" ]]; then
		icon="$paused_icon"
	else
		icon=" NOTHING PLAYING"
	fi

	widget="$icon$song"

	widget="%{A:mpc -q toggle:}$widget%{A}"
	widget="%{A3:urxvt -e ncmpcpp:}$widget%{A}"
	widget="%{A4:mpc -q prev:}$widget%{A}"
	widget="%{A5:mpc -q next:}$widget%{A}"

	echo "m$widget" > $PANEL_FIFO

	mpc idle player > /dev/null
done

