#! /bin/sh

. panel-settings

main() {
	PCM=`amixer -M get PCM | sed -rn 's/^.*\[([0-9]+)%.*$/\1/p' | uniq`
	master=`amixer -M get Master`
	
	if [[ $master =~ "[on]" ]]; then
		icon=$vol_icon
	elif [[ $master =~ "[off]" ]]; then
		icon=$muted_icon
	fi

	widget=$icon
	widget+=`makebar $PCM`

	widget="%{A:panel-volume toggle:}$widget%{A}"
	widget="%{A4:panel-volume up:}$widget%{A}"
	widget="%{A5:panel-volume down:}$widget%{A}"

	echo "v$widget" > $PANEL_FIFO
}

case $1 in
	up)
		amixer -Mq set PCM 9.5%+
		;;
	down)
		amixer -Mq set PCM 9.5%-
		;;
	toggle)
		amixer -Mq set Master toggle
		;;
esac

main
