#!/bin/bash

# SOFTWARE {{{
export BROWSER="firefox"
export EDITOR="ed"
export VISUAL="nvim"
export PAGER="less"
# }}}
# PATHS {{{
export GOPATH="$HOME/go"
export PATH="$HOME/bin:$GOPATH/bin:$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH:."

# vim: expandtab
